[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Miguel Oller <maoa22@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"

[dev-dependencies]
reqwest = "0.10.6"
tokio = "0.2.21"
