[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Miguel Oller <maoa22@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
chrono = "0.4.15"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.115"
serde-aux = "1.0.1"
sqlx = { version = "0.5.5", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
tracing = "0.1.19"
tracing-actix-web = "0.4.0-beta.4"
tracing-bunyan-formatter = "0.1.6"
tracing-futures = "0.2.4"
tracing-log = "0.1.1"
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
unicode-segmentation = "1.7.1"
uuid = { version = "0.8.1", features = ["v4"] }
validator = "0.12.0"

[dev-dependencies]
actix-rt = "2"
claim = "0.4.0"
fake = "~2.3.0"
once_cell = "1.7.2"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
serde_json = "1.0.61"
tokio = { version = "1", features = ["macros"] }
wiremock = "0.4.7"
