name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.5.1 sqlx-cli --locked sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Check sqlx metadata file
        run: cargo sqlx prepare --check

      - name: Run cargo-test
        uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo-fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install clippy
        run: rustup component add clippy

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.5.1 sqlx-cli --locked sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Run cargo-clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.5.1 sqlx-cli --locked sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Run cargo-taurpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: --ignore-tests
